version: '3.8'
services:
  mongodb:
    image: 'mongo'
    ports:
      - '27017:27017'
    volumes:
      - data:/data/db
    env_file:
      - ./env/mongodb.env
  streamfidio:
    build:
      context: .
      args:
        NODE_ENV: development
    ports:
      - '80:3001'
    volumes:
      - .:/app
      - /app/node_modules
    env_file:
      - ./env/.env
    command: npm run dev
    stdin_open: true
    depends_on:
      - mongodb

volumes:
  data: